# Generated by Django 3.1.3 on 2020-11-29 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='유저 유형'),
            preserve_default=False,
        ),
    ]
