# Generated by Django 3.1.3 on 2020-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='MBTI 유형')),
                ('list', models.CharField(max_length=255, verbose_name='직업목록')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mbti',
            field=models.CharField(default='ISTP', max_length=255, verbose_name='MBTI'),
            preserve_default=False,
        ),
    ]
